[features]
seeds = false
[programs.devnet]
gifportal = " " #paste in my key

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/personal/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"